name: React App CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push for main and releases branch
  push:
    branches:
    - main
    - releases/*

env:
  owner: akash-pal
  domain: github.io

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy-dev-test"
  deploy-dev-test:
    name: Deploy to Dev test environment
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment: 
      name: DevTest
      url: https://${{env.owner}}.${{env.domain}}/${{env.repo}}//
      
    env:
      repo: ci-cd-with-actions

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2.3.1
    
      - name: Install and Build
        run:  |
          npm install
          npm run build
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy
          folder: build # the folder the action should deploy
          
  deploy-prod:
    name: Deploy to Production Environment 
    needs: [deploy-dev-test]
    runs-on: ubuntu-latest
    environment: 
      name: Production 
      url: https://${{env.owner}}.${{env.domain}}/${{env.repo}}//
    env:
      repo: actions-workshop-prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install and Build
        run:  |
          npm install
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy
          folder: build # the folder the action should deploy
          token: ${{secrets.TOKEN}}
          repository-name: ${{env.owner}}/${{env.repo}}
        
